name: Junction
version: "1.3.0"
main: org.maboroshi.junction.Junction
loader: org.maboroshi.junction.util.LibraryLoader
description: Automate permissions and execute edition-specific commands for Java and Bedrock players using Floodgate.
author: Maboroshi
website: https://github.com/MaboroshiKobo/Junction
api-version: "1.21"
folia-supported: true
dependencies:
  server:
    floodgate:
      load: BEFORE
    LuckPerms:
      load: BEFORE
      required: false
    Vault:
      load: BEFORE
      required: false
    PlaceholderAPI:
      load: BEFORE
      required: false
