name: Junction
version: "${version}"
main: org.maboroshi.junction.Junction
loader: org.maboroshi.junction.Loader
description: Bridge the gap between Java and Bedrock crossplay. Automate permissions and execute edition-specific commands seamlessly via Geyser and Floodgate.
author: Maboroshi
website: https://github.com/MaboroshiKobo/Junction
api-version: "26.2"
folia-supported: true
dependencies:
  server:
    floodgate:
      load: BEFORE
    LuckPerms:
      load: BEFORE
      required: false
    Vault:
      load: BEFORE
      required: false
    PlaceholderAPI:
      load: BEFORE
      required: false
