name: Junction
version: "1.3.0"
main: org.maboroshi.junction.Junction
loader: org.maboroshi.junction.util.LibraryLoader
description: Automate permissions and execute edition-specific commands for Java and Bedrock players using Floodgate.
author: muhdfdeen
website: https://github.com/muhdfdeen/junction
api-version: "1.21"
dependencies:
  server:
    floodgate:
      load: BEFORE
    LuckPerms:
      load: BEFORE
      required: false
    Vault:
      load: BEFORE
      required: false
    PlaceholderAPI:
      load: BEFORE
      required: false
