name: Junction
version: '1.0-ALPHA-1'
main: com.muhdfdeen.junction.Junction
description: Automatically assigns Bedrock Edition players to groups using Floodgate and LuckPerms
author: muhdfdeen
website: https://github.com/muhdfdeen/junction
api-version: '1.21'
dependencies:
  server:
    LuckPerms:
      load: BEFORE
    floodgate:
      load: BEFORE